services:
  minio-service:
    image: 'quay.io/minio/minio'
    container_name: 'minio-service-container'
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=root
      - MINIO_ROOT_PASSWORD=minio_password_root
    command: server /data --console-address ":9001"
    volumes:
      - minio-data:/data

  minio-setup:
    image: 'minio/mc'
    depends_on:
      - minio-service
    environment:
      MC_HOST: http://root:minio_password_root@minio-service:9000

    entrypoint: >
      /bin/sh -c "
      echo Waiting for MinIO...;
      until mc alias set minio http://minio-service:9000 root minio_password_root; do sleep 1; done;
      echo Starting MinIO setup...;
      mc mb minio/dev-bucket;
      exit 0;
      "

volumes:
  minio-data:


